# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hanjiang.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
try:
    from arguments import *
except:
    import sys
    import os
    sys.path.append(os.getcwd())
    from arguments import *

class Ui_leida(object):
    def setupUi(self, leida):
        leida.setObjectName("leida")
        leida.setWindowModality(QtCore.Qt.NonModal)
        leida.resize(800, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(leida.sizePolicy().hasHeightForWidth())
        leida.setSizePolicy(sizePolicy)
        leida.setMinimumSize(QtCore.QSize(800, 400))
        leida.setMaximumSize(QtCore.QSize(800, 400))
        icon = QtGui.QIcon.fromTheme("11")
        leida.setWindowIcon(icon)
        leida.setStyleSheet("")
        self.verticalLayoutWidget = QtWidgets.QWidget(leida)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(600, 70, 160, 301))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.slider_list = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.slider_list.setContentsMargins(0, 0, 0, 0)
        self.slider_list.setObjectName("slider_list")
        self.x_slider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.x_slider.setMinimum(-1000)
        self.x_slider.setMaximum(500)
        self.x_slider.setProperty("value", int(Camera_X * 100))
        self.x_slider.setSliderPosition(int(Camera_X * 100))
        self.x_slider.setOrientation(QtCore.Qt.Horizontal)
        self.x_slider.setObjectName("x_slider")
        self.slider_list.addWidget(self.x_slider)
        self.y_slider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.y_slider.setMinimum(-500)
        self.y_slider.setMaximum(500)
        self.y_slider.setProperty("value", int(Camera_Y * 100))
        self.y_slider.setSliderPosition(int(Camera_Y * 100))
        self.y_slider.setOrientation(QtCore.Qt.Horizontal)
        self.y_slider.setObjectName("y_slider")
        self.slider_list.addWidget(self.y_slider)
        self.z_slider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.z_slider.setMinimum(-100)
        self.z_slider.setMaximum(500)
        self.z_slider.setProperty("value", int(Camera_Z * 100))
        self.z_slider.setSliderPosition(int(Camera_Z * 100))
        self.z_slider.setOrientation(QtCore.Qt.Horizontal)
        self.z_slider.setObjectName("z_slider")
        self.slider_list.addWidget(self.z_slider)
        self.pitch = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.pitch.setMinimum(-180)
        self.pitch.setMaximum(180)
        self.pitch.setProperty("value", Rotato_X)
        self.pitch.setOrientation(QtCore.Qt.Horizontal)
        self.pitch.setObjectName("pitch")
        self.slider_list.addWidget(self.pitch)
        self.yaw = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.yaw.setMinimum(-180)
        self.yaw.setMaximum(180)
        self.yaw.setProperty("value", Rotato_Yaw)
        self.yaw.setOrientation(QtCore.Qt.Horizontal)
        self.yaw.setObjectName("yaw")
        self.slider_list.addWidget(self.yaw)
        self.roll = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.roll.setEnabled(True)
        self.roll.setMinimum(-180)
        self.roll.setMaximum(180)
        self.roll.setProperty("value", Rotato_roll)
        self.roll.setOrientation(QtCore.Qt.Horizontal)
        self.roll.setObjectName("roll")
        self.slider_list.addWidget(self.roll)
        self.points_dis_Slider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.points_dis_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.points_dis_Slider.setObjectName("points_dis_Slider")
        self.points_dis_Slider.setMinimum(1)
        self.points_dis_Slider.setMaximum(100)
        self.points_dis_Slider.setProperty("value", points_distance)
        self.slider_list.addWidget(self.points_dis_Slider)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(leida)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(460, 70, 68, 301))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.args_list = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.args_list.setContentsMargins(0, 0, 0, 0)
        self.args_list.setObjectName("args_list")
        self.x_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.x_label.setMaximumSize(QtCore.QSize(100, 22))
        self.x_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.x_label.setStyleSheet("QWidget{\n"
"    background-color:rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"}")
        self.x_label.setAlignment(QtCore.Qt.AlignCenter)
        self.x_label.setObjectName("x_label")
        self.args_list.addWidget(self.x_label)
        self.y_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.y_label.setMaximumSize(QtCore.QSize(100, 22))
        self.y_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.y_label.setStyleSheet("QWidget{\n"
"    background-color:rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"}")
        self.y_label.setAlignment(QtCore.Qt.AlignCenter)
        self.y_label.setObjectName("y_label")
        self.args_list.addWidget(self.y_label)
        self.z_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.z_label.setMaximumSize(QtCore.QSize(100, 22))
        self.z_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.z_label.setStyleSheet("QWidget{\n"
"    background-color:rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"}")
        self.z_label.setAlignment(QtCore.Qt.AlignCenter)
        self.z_label.setObjectName("z_label")
        self.args_list.addWidget(self.z_label)
        self.pitch_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.pitch_label.setMaximumSize(QtCore.QSize(100, 22))
        self.pitch_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pitch_label.setStyleSheet("QWidget{\n"
"    background-color:rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"}")
        self.pitch_label.setAlignment(QtCore.Qt.AlignCenter)
        self.pitch_label.setObjectName("pitch_label")
        self.args_list.addWidget(self.pitch_label)
        self.yaw_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.yaw_label.setMaximumSize(QtCore.QSize(100, 22))
        self.yaw_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.yaw_label.setStyleSheet("QWidget{\n"
"    background-color:rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"}")
        self.yaw_label.setAlignment(QtCore.Qt.AlignCenter)
        self.yaw_label.setObjectName("yaw_label")
        self.args_list.addWidget(self.yaw_label)
        self.roll_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.roll_label.setMaximumSize(QtCore.QSize(100, 22))
        self.roll_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.roll_label.setStyleSheet("QWidget{\n"
"    background-color:rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"}")
        self.roll_label.setAlignment(QtCore.Qt.AlignCenter)
        self.roll_label.setObjectName("roll_label")
        self.args_list.addWidget(self.roll_label)
        self.points_dis_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.points_dis_label.setMaximumSize(QtCore.QSize(100, 22))
        self.points_dis_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.points_dis_label.setStyleSheet("QWidget{\n"
"    background-color:rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"}")
        self.points_dis_label.setAlignment(QtCore.Qt.AlignCenter)
        self.points_dis_label.setObjectName("points_dis_label")
        self.args_list.addWidget(self.points_dis_label)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(leida)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(540, 70, 54, 301))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.spinBox_list = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.spinBox_list.setContentsMargins(0, 0, 0, 0)
        self.spinBox_list.setObjectName("spinBox_list")
        self.x_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.x_spinBox.setMinimumSize(QtCore.QSize(0, 22))
        self.x_spinBox.setMaximumSize(QtCore.QSize(16777215, 22))
        self.x_spinBox.setMinimum(-1000)
        self.x_spinBox.setMaximum(500)
        self.x_spinBox.setProperty("value", int(Camera_X * 100))
        self.x_spinBox.setObjectName("x_spinBox")
        self.spinBox_list.addWidget(self.x_spinBox)
        self.y_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.y_spinBox.setMinimumSize(QtCore.QSize(0, 22))
        self.y_spinBox.setMaximumSize(QtCore.QSize(16777215, 22))
        self.y_spinBox.setMinimum(-500)
        self.y_spinBox.setMaximum(500)
        self.y_spinBox.setProperty("value", int(Camera_Y * 100))
        self.y_spinBox.setObjectName("y_spinBox")
        self.spinBox_list.addWidget(self.y_spinBox)
        self.z_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.z_spinBox.setMinimumSize(QtCore.QSize(0, 22))
        self.z_spinBox.setMaximumSize(QtCore.QSize(16777215, 22))
        self.z_spinBox.setMinimum(-100)
        self.z_spinBox.setMaximum(500)
        self.z_spinBox.setProperty("value", int(Camera_Z * 100))
        self.z_spinBox.setObjectName("z_spinBox")
        self.spinBox_list.addWidget(self.z_spinBox)
        self.pitch_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.pitch_spinBox.setMinimumSize(QtCore.QSize(0, 22))
        self.pitch_spinBox.setMaximumSize(QtCore.QSize(16777215, 22))
        self.pitch_spinBox.setMinimum(-180)
        self.pitch_spinBox.setMaximum(180)
        self.pitch_spinBox.setProperty("value", Rotato_X)
        self.pitch_spinBox.setObjectName("pitch_spinBox")
        self.spinBox_list.addWidget(self.pitch_spinBox)
        self.yaw_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.yaw_spinBox.setMinimumSize(QtCore.QSize(0, 22))
        self.yaw_spinBox.setMaximumSize(QtCore.QSize(16777215, 22))
        self.yaw_spinBox.setMinimum(-180)
        self.yaw_spinBox.setMaximum(180)
        self.yaw_spinBox.setProperty("value", Rotato_Yaw)
        self.yaw_spinBox.setObjectName("yaw_spinBox")
        self.spinBox_list.addWidget(self.yaw_spinBox)
        self.roll_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.roll_spinBox.setMinimumSize(QtCore.QSize(0, 22))
        self.roll_spinBox.setMaximumSize(QtCore.QSize(16777215, 22))
        self.roll_spinBox.setMinimum(-180)
        self.roll_spinBox.setMaximum(180)
        self.roll_spinBox.setProperty("value", Rotato_roll)
        self.roll_spinBox.setObjectName("roll_spinBox")
        self.spinBox_list.addWidget(self.roll_spinBox)
        self.points_dis_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.points_dis_spinBox.setMinimumSize(QtCore.QSize(0, 22))
        self.points_dis_spinBox.setMaximumSize(QtCore.QSize(16777215, 22))
        self.points_dis_spinBox.setMinimum(1)
        self.points_dis_spinBox.setMaximum(100)
        self.points_dis_spinBox.setProperty("value", points_distance)
        self.points_dis_spinBox.setObjectName("points_dis_spinBox")
        self.spinBox_list.addWidget(self.points_dis_spinBox)
        self.Camera_label = QtWidgets.QLabel(leida)
        self.Camera_label.setGeometry(QtCore.QRect(480, 20, 271, 51))
        self.Camera_label.setStyleSheet("QWidget{\n"
"    border-radius:10px;\n"
"    background-color: rgb(254, 254, 254)\n"
"}")
        self.Camera_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Camera_label.setObjectName("Camera_label")
        self.SetDefault = QtWidgets.QPushButton(leida)
        self.SetDefault.setGeometry(QtCore.QRect(690, 370, 75, 23))
        self.SetDefault.setObjectName("SetDefault")
        self.serial_data = QtWidgets.QLabel(leida)
        self.serial_data.setGeometry(QtCore.QRect(30, 10, 161, 31))
        self.serial_data.setObjectName("serial_data")
        self.graphicsView = QtWidgets.QGraphicsView(leida)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 800, 400))
        self.graphicsView.setMinimumSize(QtCore.QSize(800, 400))
        self.graphicsView.setMaximumSize(QtCore.QSize(800, 400))
        self.graphicsView.setStyleSheet("QWidget{\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.965909, y2:0.471, stop:0 rgba(152, 155, 133, 255), stop:1 rgba(183, 227, 226, 255));\n"
"}")
        self.graphicsView.setObjectName("graphicsView")
        self.img_label = QtWidgets.QLabel(leida)
        self.img_label.setGeometry(QtCore.QRect(20, 90, 400, 280))
        self.img_label.setStyleSheet("QWidget{\n"
"    border-radius:10px;\n"
"    background-color: rgb(254, 254, 254)\n"
"}")
        self.img_label.setAlignment(QtCore.Qt.AlignCenter)
        self.img_label.setObjectName("img_label")
        self.serial_data_background = QtWidgets.QLabel(leida)
        self.serial_data_background.setGeometry(QtCore.QRect(20, 40, 401, 41))
        self.serial_data_background.setStyleSheet("QWidget{\n"
"    border-radius:10px;\n"
"    background-color: rgb(254, 254, 254)\n"
"}")
        self.serial_data_background.setText("")
        self.serial_data_background.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.serial_data_background.setObjectName("serial_data_background")
        self.grass = QtWidgets.QLabel(leida)
        self.grass.setGeometry(QtCore.QRect(453, 11, 331, 361))
        self.grass.setStyleSheet("QWidget{\n"
"    border-radius:10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.965909, y2:0.471, stop:0 rgba(143, 143, 141, 255), stop:1 rgba(207, 213, 214, 200))\n"
"}")
        self.grass.setText("")
        self.grass.setObjectName("grass")
        self.serial_send = QtWidgets.QLabel(leida)
        self.serial_send.setGeometry(QtCore.QRect(33, 39, 371, 41))
        self.serial_send.setObjectName("serial_send")
        self.graphicsView.raise_()
        self.grass.raise_()
        self.verticalLayoutWidget.raise_()
        self.verticalLayoutWidget_2.raise_()
        self.verticalLayoutWidget_3.raise_()
        self.Camera_label.raise_()
        self.SetDefault.raise_()
        self.serial_data.raise_()
        self.img_label.raise_()
        self.serial_data_background.raise_()
        self.serial_send.raise_()

        self.retranslateUi(leida)
        self.roll.valueChanged['int'].connect(self.roll_spinBox.setValue) # type: ignore
        self.roll_spinBox.valueChanged['int'].connect(self.roll.setValue) # type: ignore
        self.yaw.valueChanged['int'].connect(self.yaw_spinBox.setValue) # type: ignore
        self.yaw_spinBox.valueChanged['int'].connect(self.yaw.setValue) # type: ignore
        self.pitch_spinBox.valueChanged['int'].connect(self.pitch.setValue) # type: ignore
        self.z_spinBox.valueChanged['int'].connect(self.z_slider.setValue) # type: ignore
        self.z_slider.valueChanged['int'].connect(self.z_spinBox.setValue) # type: ignore
        self.y_slider.valueChanged['int'].connect(self.y_spinBox.setValue) # type: ignore
        self.y_spinBox.valueChanged['int'].connect(self.y_slider.setValue) # type: ignore
        self.x_spinBox.valueChanged['int'].connect(self.x_slider.setValue) # type: ignore
        self.x_slider.valueChanged['int'].connect(self.x_spinBox.setValue) # type: ignore
        self.pitch.valueChanged['int'].connect(self.pitch_spinBox.setValue) # type: ignore
        self.points_dis_Slider.valueChanged['int'].connect(self.points_dis_spinBox.setValue) # type: ignore
        self.points_dis_spinBox.valueChanged['int'].connect(self.points_dis_Slider.setValue) # type: ignore
        self.SetDefault.clicked.connect(self.SetDefaultEvent)
        QtCore.QMetaObject.connectSlotsByName(leida)

    def SetDefaultEvent(self):
        self.x_slider.setProperty("value", int(Camera_X * 100))
        self.x_slider.setSliderPosition(int(Camera_X * 100))
        self.z_slider.setProperty("value", int(Camera_Z * 100))
        self.z_slider.setSliderPosition(int(Camera_Z * 100))
        self.y_slider.setProperty("value", int(Camera_Y * 100))
        self.y_slider.setSliderPosition(int(Camera_Y * 100))
        self.pitch.setProperty("value", Rotato_X)
        self.pitch.setSliderPosition(Rotato_X)
        self.yaw.setProperty("value", Rotato_Yaw)
        self.yaw.setSliderPosition(Rotato_Yaw)
        self.roll.setProperty("value", Rotato_roll)
        self.roll.setSliderPosition(Rotato_roll)
        self.points_dis_spinBox.setProperty("value", points_distance)

    def retranslateUi(self, leida):
        _translate = QtCore.QCoreApplication.translate
        leida.setWindowTitle(_translate("leida", "hanjiang-leida"))
        self.x_label.setText(_translate("leida", "<html><head/><body><p><span style=\"font-family:\'Microsoft YaHei\'; font-size:9pt; font-weight:300;\">x(cm):</span></p></body></html>"))
        self.y_label.setText(_translate("leida", "<html><head/><body><p><span style=\"font-family:\'Microsoft YaHei\'; font-size:9pt; font-weight:300;\">y(cm):</span></p></body></html>"))
        self.z_label.setText(_translate("leida", "<html><head/><body><p><span style=\"font-family:\'Microsoft YaHei\'; font-size:9pt; font-weight:300;\">z(cm):</span></p></body></html>"))
        self.pitch_label.setText(_translate("leida", "<html><head/><body><p><span style=\"font-family:\'Microsoft YaHei\'; font-size:9pt; font-weight:300;\">pitch(deg):</span></p></body></html>"))
        self.yaw_label.setText(_translate("leida", "<html><head/><body><p><span style=\"font-family:\'Microsoft YaHei\'; font-size:9pt; font-weight:300;\">yaw(deg):</span></p></body></html>"))
        self.roll_label.setText(_translate("leida", "<html><head/><body><p><span style=\"font-family:\'Microsoft YaHei\'; font-size:9pt; font-weight:300;\">roll(deg):</span></p></body></html>"))
        self.points_dis_label.setText(_translate("leida", "<html><head/><body><p><span style=\"font-family:\'Microsoft YaHei\'; font-size:9pt; font-weight:300;\">points_dis:</span></p></body></html>"))
        self.Camera_label.setText(_translate("leida", "<html><head/><body><p><span style=\"font-family:\'Microsoft YaHei\'; font-size:16pt; font-weight:500;\">Camera adjustment</span></p></body></html>"))
        self.SetDefault.setText(_translate("leida", "SetDefault"))
        self.serial_data.setText(_translate("leida", "<html><head/><body><p><span style=\"font-family:\'Microsoft YaHei\'; font-size:16pt; font-weight:300;\">serial data</span></p></body></html>"))
        self.img_label.setText(_translate("leida", "<html><head/><body><p><span style=\"font-family:\'Microsoft YaHei\'; font-size:9pt; font-weight:300;\">显示实时画面</span></p></body></html>"))
        self.serial_send.setText(_translate("leida", "<html><head/><body><p><span style=\"font-family:\'Microsoft YaHei\'; font-size:9pt; font-weight:300;\">None</span></p></body></html>"))

